spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: 765875306
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    mongodb:
      database: bookstore
      uri: mongodb://127.0.0.1:27017