spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: 765875306
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
      encoding: UTF-8
      mode: HTML5
      prefix: classpath:/templates/
      suffix: .html
      check-template: true
      cache: false